[id]
comment = "Intro session based on glass beads experiments"

[data]
#folder = r"\\klient.uib.no\\FELLES\\LAB-IT\\IFT\\resfys\\FluidFlower\\FF glass beads\\050825_glass_beads_1_150_s"
folder = "E:\\fluidflower_glass_beads\\images"
format = "JPG"                              # The format of the images
pad = 5                                     # number of relevant digits in image names, e.g. 00001.JPG
baseline = "DSC00160.JPG"                   # The baseline image
results = "E:\\fluidflower_glass_beads\\results"
log = "E:\\fluidflower_glass_beads\\log"

[specs]
dim = 2                                     # dimension of the model
width = 2.745                               # width of the model in m
height = 1.5                                # height of the model in m
porosity = 0.44                             # porosity of the medium

[depth]
measurements = "./data/depth_measurements.csv"
depth_map = "./data/depth_map.npz"

[protocols]
injection = ["./data/protocol.xlsx", "injection"]
imaging = ["./data/protocol.xlsx", "imaging"]
pressure_temperature = ["./data/protocol.xlsx", "pressure_temperature"]

[color_analysis]
format = "JPG"
baseline_images = "E:\\fluidflower_museum\\run_16\\baseline_images"
calibration_images = "E:\\fluidflower_museum\\run_16\\color_analysis"
calibration_values = "out_calibrated_values.json"

[calibration]
format = "JPG"
scaling_image = "E:\\fluidflower_museum\\run_16\\DSC25500.JPG"
#mass_images = "E:\\fluidflower_museum\\run_16\\mass_calibration"
mass_images = "E:\\fluidflower_museum\\run_16"

[analysis]
ignore_labels = [0]

[labeling]
colored_image = "./data/clean_segmented_DSC00160.png"
labels = "./data/labels.npz"
water_label = 0

[curvature.init]
horizontal_bulge = 1e-9
vertical_bulge = 0.0
[curvature.crop]
pts_src = [[381, 158], [4920, 137], [4938, 7732], [425, 7734]]
width = 2.745
height = 1.5
[curvature.bulge]
horizontal_bulge = -1.3244902496792662e-09
vertical_bulge = -4.637586886784494e-09
horizontal_center_offset = 153
vertical_center_offset = -342
[curvature.stretch]
horizontal_stretch = -3.606015332647378e-09
horizontal_center_offset = -579
vertical_stretch = -0.0
vertical_center_offset = 405