[color.path.relative_colorpath]
mode = "relative"
basis = "facies"
ignore_labels = [1, 2]                # water and top layer
resolution = 21
num_segments = 3
reference_label = 6                   # black - yellow transition.
calibration_mode = "manual"
baseline = "baseline"
data = ["calibration"]
ignore_baseline_spectrum = "none"
histogram_weighting = "threshold" # wls?
threshold_baseline = 0.0
threshold_calibration = 1e-3

[color.range.custom_hsv_range]
mode = "absolute"
color_space = "HSV"
range = [[0.1, 0.4], [0.0, 1.0], [0.6, "none"]]

[color.range.custom_hsv_range.restoration]
method = "volume_average"
ignore = ["boolean_porosity", "inner_labels"]
[color.range.custom_hsv_range.restoration.options]
rev_size = 0.005 # meters

# TODO: Allow for storing and loading this range, tuned by calibration.
#baseline = "baseline"
#data = ["calibration"]

# TODO: introduce calibration of hsv here.

[color.channel.my_red]
color_space = "RGB"
channel = "r"
# TODO: Allow for heterogneous rescaling
#baseline = "baseline"
#data = ["calibration"]


[color.channel.restricted_hue]
mode = "absolute"
color_space = "HSV"
channel = "h"

# Add mask and use same style.
[color.channel.restricted_hue.mask]
mode = "absolute"
color_space = "HSV"
range = [[0.08, 0.4], [0.3, 1.0], [0.7, "none"]]
# TODO: Allow for storing and loading this range, tuned by calibration.
#baseline = "baseline"
#data = ["calibration"]

[color.channel.restricted_hue.restoration]
method = "volume_average"
ignore = ["boolean_porosity", "inner_labels"]
[color.channel.restricted_hue.restoration.options]
rev_size = 0.005 # meters

