[rig]
dim = 2       # dimension of the model
width = 2.745 # width of the model in m
height = 1.5  # height of the model in m

[depth]
measurements = "./data/depth_measurements.csv"

[labeling]
colored_image = "./data/refined_segmented_DSC00160.png"
#colored_image = "./data/clean_segmented_DSC00160.png"

[facies]
props = "./data/facies.xlsx" # excel file with facies properties
id = [0, 1, 2, 3, 4]         #, 5]      #, 6]
[facies.0] # Facies (id as in the excel file)
labels = [0] # labels in the label image obtained from segmentation 
[facies.1]
labels = [1]
[facies.2]
labels = [2]
[facies.3]
labels = [3]
[facies.4]
labels = [4]
#[facies.5]
#labels = [5]
#[facies.6]
#labels = [6]

[curvature.init]
horizontal_bulge = 1e-9
vertical_bulge = 0.0
[curvature.crop]
pts_src = [[381, 158], [4920, 137], [4938, 7732], [425, 7734]]
width = 2.745
height = 1.5
[curvature.bulge]
horizontal_bulge = -1.3244902496792662e-09
vertical_bulge = -4.637586886784494e-09
horizontal_center_offset = 153
vertical_center_offset = -342
[curvature.stretch]
horizontal_stretch = -3.606015332647378e-09
horizontal_center_offset = -579
vertical_stretch = -0.0
vertical_center_offset = 405
