[id]
run_id = "Run 7"

# Runspecific data management
[data]
folder = "\\\\klient.uib.no\\FELLES\\LAB-IT\\IFT\\resfys\\FluidFlower\\FF2 25-26 masterdata fra 101\\Subset_20min_4h\\Experiment_7_subset_20min_4h"
baseline = "DSC22892.JPG"
results = "E:\\ff_glass_beads\\exp_7"

# Runspecific baseline images
[data.path.baseline]
paths = ["DSC22892.JPG", "DSC22888.JPG", "DSC22887.JPG"]

# Run-specific experimental metadata
[protocols]
imaging = "./protocols/imaging/exp_7.csv"
injection = "./protocols/injection/exp_7.csv"
pressure_temperature = "./protocols/pressure_temperature/exp_7.csv"
